#!/bin/bash

FIX_SCRIPT="$HOME/scripts/fix_ogg_tags.py"
MUSIC_DIR="/mnt/Vuxt-NAS/Music/"

[ "$#" -eq 0 ] && echo "Usage: ytmusic <URL>" && exit 1

yt-dlp \
  --extract-audio \
  --audio-format opus \
  --audio-quality 0 \
  --embed-metadata \
  --embed-thumbnail \
  --yes-playlist \
  --ignore-errors \
  --parse-metadata "playlist_index:%(track_number)s" \
  --replace-in-metadata title "\(Official.*?\)|\[.*?\]" "" \
  --exec "python3 \"$FIX_SCRIPT\" {}" \
  --replace-in-metadata playlist_title "^Album - " "" \
  -o "$MUSIC_DIR/%(uploader)s/%(playlist_title)s/%(playlist_index)02d - %(title)s.%(ext)s" \
  "$@"
